version: '3'

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - /data/nextcloud/db:/var/lib/mysql
    env_file:
      - db.env

  app:
    image: nextcloud:fpm
    restart: unless-stopped
    volumes:
      - /data/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    image: nginx
    restart: unless-stopped
    ports:
#      - 80:80
      - 443:443
    volumes:
      - /data/nextcloud/nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dhparam.pem:/etc/nginx/dhparam.pem:ro
      - /data/nextcloud/certs:/etc/nginx/certs:ro
    environment:
      - VIRTUAL_HOST=servhostname.local
    depends_on:
      - app
      - omgwtfssl
    networks:
      - default


  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - /data/nextcloud/certs:/certs
    environment:
      - SSL_SUBJECT=servhostname.local
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/servhostname.local.key
      - SSL_CSR=/certs/servhostname.local.csr
      - SSL_CERT=/certs/servhostname.local.crt
